os: linux
services:
   - docker

sudo: required
language: python

env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="RPLidarSDK/1.5.7"
    - CONAN_USERNAME="gdepuille"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

  matrix:
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
